import { Product } from '@/types';

// Static product catalog for fallback / SSG
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-bc-1',
    name: 'Standard Business Card',
    category: 'business_card',
    description: '85×55mm premium matte business card, 350gsm. Perfect for professionals who want a classic, understated look.',
    base_price: '299.00',
    width_mm: '85',
    height_mm: '55',
    bleed_mm: '3',
    safe_zone_mm: '3',
    paper_finish: 'matte',
    paper_gsm: 350,
    min_quantity: 100,
    thumbnail_url: null,
    is_active: true,
    pricing_tiers: [
      { quantity: 100,  unit_price: '2.99',  total_price: '299.00'  },
      { quantity: 250,  unit_price: '2.49',  total_price: '622.50'  },
      { quantity: 500,  unit_price: '1.99',  total_price: '995.00'  },
      { quantity: 1000, unit_price: '1.49',  total_price: '1490.00' },
    ],
  },
  {
    id: 'mock-bc-2',
    name: 'Gloss Business Card',
    category: 'business_card',
    description: '85×55mm premium gloss business card, 350gsm. Make a bold first impression with a high-gloss finish.',
    base_price: '349.00',
    width_mm: '85',
    height_mm: '55',
    bleed_mm: '3',
    safe_zone_mm: '3',
    paper_finish: 'gloss',
    paper_gsm: 350,
    min_quantity: 100,
    thumbnail_url: null,
    is_active: true,
    pricing_tiers: [
      { quantity: 100,  unit_price: '3.49',  total_price: '349.00'  },
      { quantity: 250,  unit_price: '2.79',  total_price: '697.50'  },
      { quantity: 500,  unit_price: '2.19',  total_price: '1095.00' },
      { quantity: 1000, unit_price: '1.69',  total_price: '1690.00' },
    ],
  },
  {
    id: 'mock-flyer-1',
    name: 'A5 Promotional Flyer',
    category: 'flyer',
    description: '148×210mm A5 single-sided flyer, 130gsm gloss. Ideal for events, promotions, and marketing campaigns.',
    base_price: '599.00',
    width_mm: '148',
    height_mm: '210',
    bleed_mm: '3',
    safe_zone_mm: '3',
    paper_finish: 'gloss',
    paper_gsm: 130,
    min_quantity: 100,
    thumbnail_url: null,
    is_active: true,
    pricing_tiers: [
      { quantity: 100,  unit_price: '5.99',  total_price: '599.00'  },
      { quantity: 250,  unit_price: '4.49',  total_price: '1122.50' },
      { quantity: 500,  unit_price: '3.49',  total_price: '1745.00' },
    ],
  },
  {
    id: 'mock-flyer-2',
    name: 'A4 Promotional Flyer',
    category: 'flyer',
    description: '210×297mm A4 single-sided flyer, 130gsm gloss. Maximum impact for retail and event promotion.',
    base_price: '899.00',
    width_mm: '210',
    height_mm: '297',
    bleed_mm: '3',
    safe_zone_mm: '3',
    paper_finish: 'gloss',
    paper_gsm: 130,
    min_quantity: 50,
    thumbnail_url: null,
    is_active: true,
    pricing_tiers: [
      { quantity: 50,   unit_price: '17.98', total_price: '899.00'  },
      { quantity: 100,  unit_price: '8.99',  total_price: '899.00'  },
      { quantity: 250,  unit_price: '6.49',  total_price: '1622.50' },
      { quantity: 500,  unit_price: '4.99',  total_price: '2495.00' },
    ],
  },
  {
    id: 'mock-label-1',
    name: 'Round Label 50mm',
    category: 'label',
    description: '50mm diameter round self-adhesive label, 90gsm gloss. Perfect for packaging, bottles, and branding.',
    base_price: '199.00',
    width_mm: '50',
    height_mm: '50',
    bleed_mm: '2',
    safe_zone_mm: '2',
    paper_finish: 'gloss',
    paper_gsm: 90,
    min_quantity: 250,
    thumbnail_url: null,
    is_active: true,
    pricing_tiers: [
      { quantity: 250,  unit_price: '0.99',  total_price: '247.50'  },
      { quantity: 500,  unit_price: '0.79',  total_price: '395.00'  },
      { quantity: 1000, unit_price: '0.59',  total_price: '590.00'  },
      { quantity: 2500, unit_price: '0.45',  total_price: '1125.00' },
    ],
  },
  {
    id: 'mock-label-2',
    name: 'Rectangle Label 90×55mm',
    category: 'label',
    description: '90×55mm rectangle self-adhesive matte label. Great for product packaging and address labels.',
    base_price: '249.00',
    width_mm: '90',
    height_mm: '55',
    bleed_mm: '2',
    safe_zone_mm: '2',
    paper_finish: 'matte',
    paper_gsm: 90,
    min_quantity: 250,
    thumbnail_url: null,
    is_active: true,
    pricing_tiers: [
      { quantity: 250,  unit_price: '0.99',  total_price: '247.50'  },
      { quantity: 500,  unit_price: '0.79',  total_price: '395.00'  },
      { quantity: 1000, unit_price: '0.59',  total_price: '590.00'  },
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  business_card: 'Business Cards',
  flyer:         'Flyers',
  label:         'Labels',
  poster:        'Posters',
  brochure:      'Brochures',
};

export const FINISH_LABELS: Record<string, string> = {
  matte:      'Premium Matte',
  gloss:      'High Gloss',
  soft_touch: 'Soft Touch',
  uncoated:   'Uncoated',
};
